### PR TITLE
Adding Boston, MA, USA

### PR DESCRIPTION
**Pull request by ethanstrominger**

### CODE REVIEW

**Comment by rradczewski** [comment]
Thanks! Couldn't figure out the issue on my mobile, glad you found it!

Welcome  🎉

**Comment by rradczewski** [comment]
There's currently no way to add more then one url, but if you use the Meetup page the map will automatically fetch your next event if people click on the pop-up, just FYI 😊

**Comment by ethanstrominger** [comment]
Hmmm...I think I still prefer the Boston Software Crafters website - just created the website.  It provides more info than if they just go to the event and I will be adding more info to it.  Thanks!!

**Comment by ethanstrominger** [comment]
Thanks for merging this - that is great to see it on the map!  I also mention Software Crafters at https://bostonsoftwarecrafters.wordpress.com/forums/.

**Pull request merged**
