### PR TITLE
Make CoC a mandatory field

### PR DESCRIPTION
**Pull request by rradczewski**
Requires these conferences to add their (/a) Code of Conduct:

- [x] Codefreeze
- [x] Software Craftsmanship Unconference
- [x] SoCraTes Canaries
- [x] SoCraTes Day Switzerland
- [x] Software Engineering Camp

### CODE REVIEW

**Comment by rradczewski** [comment]
Hi @rinkkasatiainen, @mdclement, @rubendm92, (Socrates Day CH people), @poschi3 - do you mind looking into updating your conference with a link to your code of conduct? If you post it here, I can work it into the PR right away :+1:

**Comment by poschi3** [comment]
Hi @rradczewski I forwarded your request to the organization team of the Software Engineering Camp

**Comment by rubendm92** [comment]
Code of conduct for Socrates Canaries @rradczewski  https://github.com/softwarecrafters/website/pull/74 :)

**Comment by franziskas** [comment]
Working on one for codefreeze, first draft is done so just waiting for feedback to add it. https://github.com/rinkkasatiainen/codefreeze.fi/issues/143

**Comment by franziskas** [comment]
@patbaumgartner care to add the link for SoCraTes CH?

**Comment by patbaumgartner** [comment]
Thanks! I will have a look at it and add it to SoCraTes CH Website. Since
we need to change more there, it will take some days. Thank you very much!

**Comment by coderbyheart** [comment]
When will the CoC become mandatory?

**Comment by coderbyheart** [comment]
Codefreeze now has a Code of Conduct: https://codefreeze.fi/#code-of-conduct
PR: https://github.com/rinkkasatiainen/codefreeze.fi/pull/153

**Comment by coderbyheart** [comment]
I would really like to help make the Code of Conduct mandatory for listings on https://www.softwarecrafters.org/. What can I do to help? @rradczewski

**Comment by coderbyheart** [comment]
@rradczewski I've appended your PR, so you can't use the GitHub review feature. Nevertheless please review!

**Comment by jukecraft** [comment]
Appoved :)

**Pull request merged**
