### PR TITLE
Add AgileCrete open space unconference

### PR DESCRIPTION
**Pull request by gsaslis**
includes dates for 2019, in its 6th year

### CODE REVIEW

**Comment by franziskas** [comment]
@gsaslis the website says 5th-7th of September and KOLYMVARI - is it ok that this entry doesn't match?

**Comment by gsaslis** [comment]
great catch @franziskas ! 

sorry about that - got confused with the accommodation packages that I was working on at that same time, as those start on the 4th (people usually arrive a day early). 

Also fixed the spelling ;) 

Thank you!!!

**Comment by gsaslis** [comment]
(btw - might be worth squashing when merging, so as not to pollute the history too much)

**Comment by franziskas** [comment]
I usually do :)

**Pull request merged**
