### PR TITLE
Adding Mob Programming New England conference

### PR DESCRIPTION
**Pull request by ethanstrominger**

### CODE REVIEW

**Comment by franziskas** [comment]
@ethanstrominger yay! Would you consider linking to your Code of Conduct from the event's main website?

**Comment by rradczewski** [comment]
Shall we merge this as it is @franziskas ?

**Comment by franziskas** [comment]
Depends on whether a public CoC is a requirement. I'd strongly suggest we make it one but I'd leave the final decision to you

**Comment by rradczewski** [comment]
Just spoke to @ethanstrominger, they're going to link to the CoC on their website tomorrow. As it's already linked to here, I'll proceed with merging it.

> I'd strongly suggest we make it one but I'd leave the final decision to you

I think that's a reasonable goal, I'll start reaching out to the other conferences which don't list their CoC here yet. Once they're all taking care of, we can change `.code-of-conduct` to be a mandatory field. 

> Codefreeze
Software Craftsmanship Unconference
SoCraTes Canaries
SoCraTes Day Switzerland
Software Engineering Camp

**Comment by rradczewski** [comment]
Woops, looks like your coordinates are a bit wrong @ethanstrominger. Do you mind fixing that before I merge? Might just be lat/long needing to be swapped out :+1: 

image

**Comment by ethanstrominger** [comment]
@franziskas  I modified code of conduct URL and switched the coordinates.  Note in google maps, when I put coordinates in the search box in this order: 42.484449, -71.191560 it works.  When I put the coordinates in the reverse order, as they are in the pull request, it goes to Antartica, in the same location shown in the image above.

**Comment by ethanstrominger** [comment]
@franziskas  Can you review again?

**Pull request merged**
